services:
  - type: web
    name: portfolio-professeur
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://portfolio-professeur.onrender.com
      - key: ASSET_URL
        value: https://portfolio-professeur.onrender.com